project_name: kubectl-pvcmount
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: kubectl-pvcmount
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
brews:
  - name: kubectl-pvcmount
    repository:
      owner: stenstromen
      name: homebrew-tap
    commit_author:
      name: stenstromen
    homepage: https://github.com/Stenstromen/kubectl-pvcmount
    description: Go binary for temporary mounting of PVCs
    directory: Formula
