apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pvcmount
spec:
  version: "v1.0.0"
  shortDescription: Go binary for mounting persistent volumes.
  homepage: https://github.com/Stenstromen/kubectl-pvcmount
  description: |
    Go binary for temporary mounting of PVCs to a pod. 
    This is useful for debugging purposes or for copying data from a PVC to another location.
    The pvc is mounted to /mnt in a pod with a busybox container.
    Examples:
    `$ kubectl pvcmount pvc -p pvc-name -n namespace-containing-pvc`
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_darwin_amd64.tar.gz
      sha256: ${sha256}
      bin: "./kubectl-pvcmount"
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_darwin_arm64.tar.gz
      sha256: ${sha256}
      bin: "./kubectl-pvcmount"
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_linux_amd64.tar.gz
      sha256: ${sha256}
      bin: "./kubectl-pvcmount"
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_linux_arm64.tar.gz
      sha256: ${sha256}
      bin: "./kubectl-pvcmount"